name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      -main
  
jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.7
        options: --privileged
        ports:
          - 3000:3000

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install Backend dependencies
        run: |
          cd backend
          npm install

      - name: Run Backend build
        run:  |
          cd backend
          npm run build

      - name: Run Backend Tests
        run:  |
          cd backend
          npm test
        
      - name: Install Frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Run Frontend build
        run: |
          cd frontend
          npm run build

      - name: Build backend docker image
        run: docker build -t du-music-backend:latest ./backend